### ISSUE TITLE
Fix links in meta data table

### ISSUE THREAD

**Issue by nconrad** [nconrad/model-viewer#2]

**Comment by nconrad** [comment]
reopening due to typo in commit.

**Comment by nconrad** [comment]
@cshenry and @janakagithub, when following genome links to kbase, the user has to be logged into KBase to view the data.  Unfortunate.  There's also no message on the landing page stating this.

**Comment by janakagithub** [comment]
Is this the case for data in  "public" workspaces ?

**Comment by nconrad** [comment]
Yep.

**Comment by janakagithub** [comment]
Yuk!

**Comment by cshenry** [comment]
Is it not trivial to stage our own copy of the LP on our system without this restriction? If so, I think this is exactly what we should do� and the sooner we migrate to PATRIC WS the better� but not before submission of the paper of course.
Chris

**Comment by nconrad** [comment]
I'd say it's not trivial... considering the time involved and little long-term impact (and considering of the migration).    Besides, I already had that working at one point :p
